# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

openapi: 3.0.0
info:
  title: Open Data Hub Swagger
  description: |
    Welcome to the Open Data Hub Swagger instance.

    This is just a landing page. To check out the APIs, start by selecting a definition on the top right.
    
    [More information on the APIs](https://api.opendatahub.com)
    
  contact:
    name: Open Data Hub
    url: https://opendatahub.com
    email: help@opendatahub.com
  version: ""
paths: {}
