openapi: 3.0.1
info:
  title: Open Data Hub Central Swagger
  description: |
    <div style="text-align: center; border: 3px solid black; padding: 20px; margin-bottom: 40px">
      To use this Swagger instance, just add <code>?url=https://link-to-your-spec</code>
      to the URL above. You can use Swagger and OpenAPI specifications.
    </div>
  contact:
    name: Open Data Hub
    url: https://opendatahub.bz.it
    email: help@opendatahub.bz.it
  version: "X"
paths: {}
