# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
      no_cache: true
    volumes:
      - ./:/code
    env_file: .env
    tty: true
    ports:
      - 8999:8080
