version = 1
SPDX-PackageName = "odh-swaggerui"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/odh-swaggerui"

[[annotations]]
path = [".github/**", "config/**", "infrastructure/**", ".pre-commit-config.yaml", ".editorconfig", ".env.example"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
